version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    container_name: presensi_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/opt/bitnami/php/etc/conf.d
    networks:
      - presensi_network
    depends_on:
      - db
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: presensi_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./storage/logs/nginx:/var/log/nginx
    networks:
      - presensi_network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: presensi_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: presensi_jkn
      MYSQL_USER: jkn_user
      MYSQL_PASSWORD: 'Zachran#recodex15'
      MYSQL_ROOT_PASSWORD: 'RootPassword123!'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - presensi_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: presensi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - presensi_network

  # PhpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: presensi_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: jkn_user
      PMA_PASSWORD: 'Zachran#recodex15'
    ports:
      - "8080:80"
    networks:
      - presensi_network
    depends_on:
      - db

  # SSL Certificate Manager
  certbot:
    image: certbot/certbot
    container_name: presensi_certbot
    restart: "no"
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./laravel-app:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html/public --email admin@jakakuasanusantara.web.id --agree-tos --no-eff-email -d jakakuasanusantara.web.id -d www.jakakuasanusantara.web.id

volumes:
  mysql_data:
  redis_data:

networks:
  presensi_network:
    driver: bridge
